webapps2023/authy/urls.py
from django.urls import path
from .views import login_page, login_user, logout_user, change_password
from django.conf.urls import include

app_name = 'authy'
urlpatterns = [
    path('login/', login_page, name='login_page'),
    path('login_user', login_user, name='login_user'),
    path('register', include('register.urls')),
    # path('register_user', register_user, name='register_user'),
    path('logout', logout_user, name='logout_user'),
    path('change_password', change_password, name='change_password'),
]

webapps2023/webapps2023/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from .views import home_page

app_name = 'webapps2023'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home_page'),
    path('auth/', include('authy.urls')),
    path('app/', include('payapp.urls')),
    path('conversion/', include('payapp.conversion_urls')),
]

webapps2023/templates/home/index.html
{% extends "base/base.html" %}
{% load static %}
{%  block content %}
<div class="d-flex vh-100 text-center text-bg-dark"
     style="text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto pt-4 pt-xl-5">
            <div class="logo">
                <a class="text-decoration-none" href="{% url 'home_page' %}">
                    <h4 class="text-white">Ca$hConnect</h4>
                </a>
                <p class="fw-lighter text-white-50">Connecting you to the money you need</p>
            </div>
        </header>
        <main class="px-3">
            <h1>Fast, Easy, and Secure Payments</h1>
            <p class="lead">Say goodbye to complicated payment processes and hello to
                <span class="primary-bg p-1" style="font-family: 'Bungee';">Ca$hConnect</span>.
                Our platform is fast, easy, and secure, allowing you to send, receive and request payments quickly and
                safely.</p>
            <p class="lead">
                <a class="btn btn-lg btn-light fw-bold border-white bg-white" href="{% url 'authy:login_page' %}">Get
                    Started</a></p>
        </main>
        <footer class="mt-auto text-white-50">
            <p>Cover template for&nbsp;
                <a class="text-decoration-none text-white" href="https://getbootstrap.com/" target="_blank">Bootstrap</a>, by&nbsp;
                <a class="text-white" href="https://oye.engineer/" target="_blank">Oy3</a>
            </p>
        </footer>
    </div>
</div>
{%  endblock  %}