webapps2023/authy/urls.py
from django.urls import path
from .views import login_page, login_user, logout_user, change_password
from django.conf.urls import include

app_name = 'authy'
urlpatterns = [
    path('login/', login_page, name='login_page'),
    path('login_user', login_user, name='login_user'),
    path('register', include('register.urls')),
    # path('register_user', register_user, name='register_user'),
    path('logout', logout_user, name='logout_user'),
    path('change_password', change_password, name='change_password'),
]

webapps2023/payapp/urls.py
from django.urls import path
from .views import dashboard_page, transfer_page, transactions_page, settings_page, help_page, update_profile, get_countries, search_user, create_transaction, accept_fund_request, cancel_fund_request, request_money, search_transactions


app_name = 'payapp'
urlpatterns = [
    path('', dashboard_page, name='dashboard_page'),
    path('transfer', transfer_page, name='transfer_page'),
    path('transactions', transactions_page, name='transactions_page'),
    path('settings', settings_page, name='settings_page'),
    path('help', help_page, name='help_page'),
    path('update_profile', update_profile, name='update_profile'),
    path('get_countries', get_countries, name='get_countries'),
    path('search_user', search_user, name='search_user'),
    path('create_transaction', create_transaction, name='create_transaction'),
    path('cancel_fund_request/<int:transaction_id>/', cancel_fund_request, name='cancel_fund_request'),
    # path('accept_fund_request/<int:transaction_id>/', accept_fund_request, name='accept_fund_request'),
    path('accept_fund_request/<int:transaction_id>/<int:sender_id>/<int:receiver_id>/<str:amount_from>/<str:amount_to>/', accept_fund_request, name='accept_fund_request'),
    path('request_money', request_money, name='request_money'),
    path('search_transactions', search_transactions, name='search_transactions'),

]

webapps2023/webapps2023/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from .views import home_page

app_name = 'webapps2023'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home_page'),
    path('auth/', include('authy.urls')),
    path('app/', include('payapp.urls')),
    path('conversion/', include('payapp.conversion_urls')),
]

webapps2023/payapp/models.py
from django.db import models

# Create your models here.

webapps2023/payapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, JsonResponse
from django.conf import settings
from currency.models import Currency
from authy.models import UserWallet, Transaction
from json import dumps
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from django.forms.models import model_to_dict
import requests
from datetime import datetime, timedelta
from django.db import transaction as atomic_transaction
from django.db.models import Sum
from django.core import serializers

import os

User = get_user_model()


def get_countries(request):
    countries = [
        {"name": 'Afghanistan', "code": 'AF'},
        {"name": 'Åland Islands', "code": 'AX'},
        {"name": 'Albania', "code": 'AL'},
        {"name": 'Algeria', "code": 'DZ'},
        {"name": 'American Samoa', "code": 'AS'},
        {"name": 'AndorrA', "code": 'AD'},
        {"name": 'Angola', "code": 'AO'},
        {"name": 'Anguilla', "code": 'AI'},
        {"name": 'Antarctica', "code": 'AQ'},
        {"name": 'Antigua and Barbuda', "code": 'AG'},
        {"name": 'Argentina', "code": 'AR'},
        {"name": 'Armenia', "code": 'AM'},
        {"name": 'Aruba', "code": 'AW'},
        {"name": 'Australia', "code": 'AU'},
        {"name": 'Austria', "code": 'AT'},
        {"name": 'Azerbaijan', "code": 'AZ'},
        {"name": 'Bahamas', "code": 'BS'},
        {"name": 'Bahrain', "code": 'BH'},
        {"name": 'Bangladesh', "code": 'BD'},
        {"name": 'Barbados', "code": 'BB'},
        {"name": 'Belarus', "code": 'BY'},
        {"name": 'Belgium', "code": 'BE'},
        {"name": 'Belize', "code": 'BZ'},
        {"name": 'Benin', "code": 'BJ'},
        {"name": 'Bermuda', "code": 'BM'},
        {"name": 'Bhutan', "code": 'BT'},
        {"name": 'Bolivia', "code": 'BO'},
        {"name": 'Bosnia and Herzegovina', "code": 'BA'},
        {"name": 'Botswana', "code": 'BW'},
        {"name": 'Bouvet Island', "code": 'BV'},
        {"name": 'Brazil', "code": 'BR'},
        {"name": 'British Indian Ocean Territory', "code": 'IO'},
        {"name": 'Brunei Darussalam', "code": 'BN'},
        {"name": 'Bulgaria', "code": 'BG'},
        {"name": 'Burkina Faso', "code": 'BF'},
        {"name": 'Burundi', "code": 'BI'},
        {"name": 'Cambodia', "code": 'KH'},
        {"name": 'Cameroon', "code": 'CM'},
        {"name": 'Canada', "code": 'CA'},
        {"name": 'Cape Verde', "code": 'CV'},
        {"name": 'Cayman Islands', "code": 'KY'},
        {"name": 'Central African Republic', "code": 'CF'},
        {"name": 'Chad', "code": 'TD'},
        {"name": 'Chile', "code": 'CL'},
        {"name": 'China', "code": 'CN'},
        {"name": 'Christmas Island', "code": 'CX'},
        {"name": 'Cocos (Keeling) Islands', "code": 'CC'},
        {"name": 'Colombia', "code": 'CO'},
        {"name": 'Comoros', "code": 'KM'},
        {"name": 'Congo', "code": 'CG'},
        {"name": 'Congo, The Democratic Republic of the', "code": 'CD'},
        {"name": 'Cook Islands', "code": 'CK'},
        {"name": 'Costa Rica', "code": 'CR'},
        {"name": 'Cote D\'Ivoire', "code": 'CI'},
        {"name": 'Croatia', "code": 'HR'},
        {"name": 'Cuba', "code": 'CU'},
        {"name": 'Cyprus', "code": 'CY'},
        {"name": 'Czech Republic', "code": 'CZ'},
        {"name": 'Denmark', "code": 'DK'},
        {"name": 'Djibouti', "code": 'DJ'},
        {"name": 'Dominica', "code": 'DM'},
        {"name": 'Dominican Republic', "code": 'DO'},
        {"name": 'Ecuador', "code": 'EC'},
        {"name": 'Egypt', "code": 'EG'},
        {"name": 'El Salvador', "code": 'SV'},
        {"name": 'Equatorial Guinea', "code": 'GQ'},
        {"name": 'Eritrea', "code": 'ER'},
        {"name": 'Estonia', "code": 'EE'},
        {"name": 'Ethiopia', "code": 'ET'},
        {"name": 'Falkland Islands (Malvinas)', "code": 'FK'},
        {"name": 'Faroe Islands', "code": 'FO'},
        {"name": 'Fiji', "code": 'FJ'},
        {"name": 'Finland', "code": 'FI'},
        {"name": 'France', "code": 'FR'},
        {"name": 'French Guiana', "code": 'GF'},
        {"name": 'French Polynesia', "code": 'PF'},
        {"name": 'French Southern Territories', "code": 'TF'},
        {"name": 'Gabon', "code": 'GA'},
        {"name": 'Gambia', "code": 'GM'},
        {"name": 'Georgia', "code": 'GE'},
        {"name": 'Germany', "code": 'DE'},
        {"name": 'Ghana', "code": 'GH'},
        {"name": 'Gibraltar', "code": 'GI'},
        {"name": 'Greece', "code": 'GR'},
        {"name": 'Greenland', "code": 'GL'},
        {"name": 'Grenada', "code": 'GD'},
        {"name": 'Guadeloupe', "code": 'GP'},
        {"name": 'Guam', "code": 'GU'},
        {"name": 'Guatemala', "code": 'GT'},
        {"name": 'Guernsey', "code": 'GG'},
        {"name": 'Guinea', "code": 'GN'},
        {"name": 'Guinea-Bissau', "code": 'GW'},
        {"name": 'Guyana', "code": 'GY'},
        {"name": 'Haiti', "code": 'HT'},
        {"name": 'Heard Island and Mcdonald Islands', "code": 'HM'},
        {"name": 'Holy See (Vatican City State)', "code": 'VA'},
        {"name": 'Honduras', "code": 'HN'},
        {"name": 'Hong Kong', "code": 'HK'},
        {"name": 'Hungary', "code": 'HU'},
        {"name": 'Iceland', "code": 'IS'},
        {"name": 'India', "code": 'IN'},
        {"name": 'Indonesia', "code": 'ID'},
        {"name": 'Iran, Islamic Republic Of', "code": 'IR'},
        {"name": 'Iraq', "code": 'IQ'},
        {"name": 'Ireland', "code": 'IE'},
        {"name": 'Isle of Man', "code": 'IM'},
        {"name": 'Israel', "code": 'IL'},
        {"name": 'Italy', "code": 'IT'},
        {"name": 'Jamaica', "code": 'JM'},
        {"name": 'Japan', "code": 'JP'},
        {"name": 'Jersey', "code": 'JE'},
        {"name": 'Jordan', "code": 'JO'},
        {"name": 'Kazakhstan', "code": 'KZ'},
        {"name": 'Kenya', "code": 'KE'},
        {"name": 'Kiribati', "code": 'KI'},
        {"name": 'Korea, Democratic People\'S Republic of', "code": 'KP'},
        {"name": 'Korea, Republic of', "code": 'KR'},
        {"name": 'Kuwait', "code": 'KW'},
        {"name": 'Kyrgyzstan', "code": 'KG'},
        {"name": 'Lao People\'S Democratic Republic', "code": 'LA'},
        {"name": 'Latvia', "code": 'LV'},
        {"name": 'Lebanon', "code": 'LB'},
        {"name": 'Lesotho', "code": 'LS'},
        {"name": 'Liberia', "code": 'LR'},
        {"name": 'Libyan Arab Jamahiriya', "code": 'LY'},
        {"name": 'Liechtenstein', "code": 'LI'},
        {"name": 'Lithuania', "code": 'LT'},
        {"name": 'Luxembourg', "code": 'LU'},
        {"name": 'Macao', "code": 'MO'},
        {"name": 'Macedonia, The Former Yugoslav Republic of', "code": 'MK'},
        {"name": 'Madagascar', "code": 'MG'},
        {"name": 'Malawi', "code": 'MW'},
        {"name": 'Malaysia', "code": 'MY'},
        {"name": 'Maldives', "code": 'MV'},
        {"name": 'Mali', "code": 'ML'},
        {"name": 'Malta', "code": 'MT'},
        {"name": 'Marshall Islands', "code": 'MH'},
        {"name": 'Martinique', "code": 'MQ'},
        {"name": 'Mauritania', "code": 'MR'},
        {"name": 'Mauritius', "code": 'MU'},
        {"name": 'Mayotte', "code": 'YT'},
        {"name": 'Mexico', "code": 'MX'},
        {"name": 'Micronesia, Federated States of', "code": 'FM'},
        {"name": 'Moldova, Republic of', "code": 'MD'},
        {"name": 'Monaco', "code": 'MC'},
        {"name": 'Mongolia', "code": 'MN'},
        {"name": 'Montserrat', "code": 'MS'},
        {"name": 'Morocco', "code": 'MA'},
        {"name": 'Mozambique', "code": 'MZ'},
        {"name": 'Myanmar', "code": 'MM'},
        {"name": 'Namibia', "code": 'NA'},
        {"name": 'Nauru', "code": 'NR'},
        {"name": 'Nepal', "code": 'NP'},
        {"name": 'Netherlands', "code": 'NL'},
        {"name": 'Netherlands Antilles', "code": 'AN'},
        {"name": 'New Caledonia', "code": 'NC'},
        {"name": 'New Zealand', "code": 'NZ'},
        {"name": 'Nicaragua', "code": 'NI'},
        {"name": 'Niger', "code": 'NE'},
        {"name": 'Nigeria', "code": 'NG'},
        {"name": 'Niue', "code": 'NU'},
        {"name": 'Norfolk Island', "code": 'NF'},
        {"name": 'Northern Mariana Islands', "code": 'MP'},
        {"name": 'Norway', "code": 'NO'},
        {"name": 'Oman', "code": 'OM'},
        {"name": 'Pakistan', "code": 'PK'},
        {"name": 'Palau', "code": 'PW'},
        {"name": 'Palestinian Territory, Occupied', "code": 'PS'},
        {"name": 'Panama', "code": 'PA'},
        {"name": 'Papua New Guinea', "code": 'PG'},
        {"name": 'Paraguay', "code": 'PY'},
        {"name": 'Peru', "code": 'PE'},
        {"name": 'Philippines', "code": 'PH'},
        {"name": 'Pitcairn', "code": 'PN'},
        {"name": 'Poland', "code": 'PL'},
        {"name": 'Portugal', "code": 'PT'},
        {"name": 'Puerto Rico', "code": 'PR'},
        {"name": 'Qatar', "code": 'QA'},
        {"name": 'Reunion', "code": 'RE'},
        {"name": 'Romania', "code": 'RO'},
        {"name": 'Russian Federation', "code": 'RU'},
        {"name": 'RWANDA', "code": 'RW'},
        {"name": 'Saint Helena', "code": 'SH'},
        {"name": 'Saint Kitts and Nevis', "code": 'KN'},
        {"name": 'Saint Lucia', "code": 'LC'},
        {"name": 'Saint Pierre and Miquelon', "code": 'PM'},
        {"name": 'Saint Vincent and the Grenadines', "code": 'VC'},
        {"name": 'Samoa', "code": 'WS'},
        {"name": 'San Marino', "code": 'SM'},
        {"name": 'Sao Tome and Principe', "code": 'ST'},
        {"name": 'Saudi Arabia', "code": 'SA'},
        {"name": 'Senegal', "code": 'SN'},
        {"name": 'Serbia and Montenegro', "code": 'CS'},
        {"name": 'Seychelles', "code": 'SC'},
        {"name": 'Sierra Leone', "code": 'SL'},
        {"name": 'Singapore', "code": 'SG'},
        {"name": 'Slovakia', "code": 'SK'},
        {"name": 'Slovenia', "code": 'SI'},

webapps2023/templates/payapp/transfer.html
{% extends "base/base.html" %}
{% load static %}
{%  block content %}

{% include 'base/header_app_base.html' %}

<div class="container-fluid">
    <div class="row">
        {% include 'base/sidebar_base.html' %}

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-5">
            <div
                    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-5 border-bottom">
                <h3>Transfer</h3>
            </div>
            <div class="row">
                <div class="col-md-12 col-lg-5 col-xl-5 col-xxl-4">
                    <h4 class="mb-4">Account Overview</h4>
                    <div class="bg-dark text-white">
                        <div class="p-3">
                            <p class="fw-lighter" style="font-size: 12px;">Balance</p>
                            <h2 class="fw-bold">{{currency_code.upper}} {{ wallet.balance }}</h2>
                            <hr>
                            <span class="fw-lighter" style="font-size: 12px;">Username</span>
                            <p>{{ auth_user.username }}</p><span class="fw-lighter" style="font-size: 12px;">Account Name</span>
                            <p>{{ auth_user.first_name }} {{ auth_user.last_name}}</p>
                        </div>
                        <button class="btn btn-light form-control rounded-0 p-3 border-0 fw-bold" type="button"
                                style="background-color: #c6b5f2 !important;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                                 viewBox="0 0 16 16" class="bi bi-box-arrow-up-right fs-5 me-2">
                                <path fill-rule="evenodd"
                                      d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z">
                                </path>
                                <path fill-rule="evenodd"
                                      d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z">
                                </path>
                            </svg>
                            Share details
                        </button>
                        <button class="btn btn-light form-control rounded-0 p-3 border-0 fw-bold" type="button"
                                style="background-color: #fec0a7 !important;" data-bs-toggle="modal"
                                data-bs-target="#requestModal">
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                                 viewBox="0 0 16 16" class="bi bi-cash fs-5 me-2">
                                <path d="M8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"></path>
                                <path
                                        d="M0 4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V6a2 2 0 0 1-2-2H3z">
                                </path>
                            </svg>
                            Request payment
                        </button>
                    </div>
                </div>
                <div
                        class="col-md-12 col-lg-7 col-xl-7 col-xxl-7 my-sm-5 my-5 my-md-5 my-lg-0 px-3 px-sm-5 px-md-0 ps-lg-3 ps-xl-5">
                    <h4 class="mb-4">Transfer to</h4>
                    <form method="post" action="{% url 'payapp:create_transaction' %}">
                        {% csrf_token %}
                        <fieldset>
                            <div class="mb-4">
                                <label class="form-label">Beneficiary</label>

                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" id="searchUserInput" name="searchUserInput"
                                           placeholder="Search by username or email address"
                                           aria-label="Recipient's username" aria-describedby="searchBtn" required>
                                    <button class="btn btn-primary" type="button" id="searchBtn">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                                             viewBox="0 0 24 24"
                                             fill="none"
                                             class="fs-5 text-white fw-bold">
                                            <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z"
                                                  stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                                  stroke-linejoin="round"></path>
                                        </svg>
                                    </button>
                                </div>
                            </div>
                            <input type="hidden" id="sent_to" name="sent_to">

                            <input class="form-control mb-4" type="text" disabled="" readonly=""
                                   id="receiverFullname" name="receiverFullname" placeholder="Full name shows here...">
                            <div class="input-group mb-4">
                                <span class="bg-white input-group-text text-black-50">
                                    {{currency_code.upper}}
                                </span>
                                <input class="form-control" type="text" id="amountInput" name="amountInput"
                                       placeholder="Amount" required>
                            </div>
                            <div class="form-floating mb-4">
                                <textarea class="form-control" id="refInput" name="refInput"
                                          placeholder="References"></textarea>
                                <label class="form-label text-black-50" for="refInput">Reference (optional)</label>
                            </div>
                            <button class="btn btn-dark form-control" type="submit">Send</button>
                        </fieldset>
                    </form>
                </div>
            </div>
        </main>


    </div>
</div>

<!--{% if display_modal %}--> <!--{% endif %}-->
<div class="modal fade" role="dialog" tabindex="-1" id="requestModal" data-bs-backdrop="static"
     data-bs-keyboard="false" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Request Money</h4>
                <button class="btn-close" type="button" aria-label="Close"
                        data-bs-dismiss="modal"></button>
            </div>
            <form method="post" action="{% url 'payapp:request_money' %}">
                {% csrf_token %}
                <fieldset>
                    <div class="modal-body">

                        <div class="mb-4">
                            <label class="form-label">From:</label>
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" id="searchReqUserInput" name="searchUserInput"
                                       placeholder="Search by username or email address"
                                       aria-label="Recipient's username" aria-describedby="searchBtn" required>
                                <button class="btn btn-secondary" type="button" id="searchReqBtn">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                                         viewBox="0 0 24 24"
                                         fill="none"
                                         class="fs-5 text-white fw-bold">
                                        <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z"
                                              stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                              stroke-linejoin="round"></path>
                                    </svg>
                                </button>
                            </div>

                        </div>

                        <input type="hidden" id="req_from" name="req_from">

                        <input id="accFullnameInput" name="accFullnameInput" class="form-control mb-4" type="text"
                               disabled="" readonly=""
                               placeholder="Full name shows here...">
                        <div class="input-group mb-4">
                        <span class="bg-white input-group-text text-black-50">
                                    {{currency_code.upper}}
                                </span>
                            <input id="reqAmountInput" name="reqAmountInput" class="form-control" type="text"
                                   placeholder="Amount" required>
                        </div>
                        <div class="form-floating">
                            <textarea class="form-control" id="reqRef" name="reqRef"
                                      placeholder="References"></textarea>
                            <label class="form-label text-black-50" for="reqRef">Reference
                                (optional)</label>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-light" type="button"
                                data-bs-dismiss="modal">Cancel
                        </button>
                        <button class="btn btn-success" type="submit">Request</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>


<script>
    const searchBtn = document.getElementById('searchBtn');
    searchBtn.addEventListener('click', function () {
        hideError();

        const fd = new FormData();
        console.log(fd);

        const userInput = document.getElementById('searchUserInput').value.toLowerCase();
        const receiverInput = document.getElementById('sent_to');
        let receiverFullname = document.getElementById('receiverFullname');

        if (!userInput) {
            showError('Search field is empty', true);
        } else {
            fd.append("search_user", userInput);
            $.ajax({
                url: "/app/search_user",
                type: "POST",
                data: {search_user: userInput},
                success: function (response) {
                    // alert('Success');
                    const {status, msg, data} = response
                    console.log(data);
                    receiverInput.value = data.username;
                    receiverFullname.value = data.first_name + ' ' + data.last_name;
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    showError(JSON.parse(jqXHR.responseText).msg, true);
                    // alert(JSON.parse(jqXHR.responseText).msg);
                    console.log(JSON.parse(jqXHR.responseText).msg);
                }
            });
        }

    }, false);

    const searchReqBtn = document.getElementById('searchReqBtn');
    searchReqBtn.addEventListener('click', function () {
        hideError();

        const fd = new FormData();
        const userInput = document.getElementById('searchReqUserInput').value.toLowerCase();
        const accInput = document.getElementById('req_from');
        let accFullname = document.getElementById('accFullnameInput');

        if (!userInput) {
            showError('Search field is empty', true);
        } else {
            fd.append("search_user", userInput);
            $.ajax({
                url: "/app/search_user",
                type: "POST",
                data: {search_user: userInput},
                success: function (response) {
                    const {status, msg, data} = response
                    accInput.value = data.username;
                    accFullname.value = data.first_name + ' ' + data.last_name;
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    showError(JSON.parse(jqXHR.responseText).msg, true);
                    console.log(JSON.parse(jqXHR.responseText).msg);
                }
            });
        }

    }, false);
</script>

{%  endblock  %}