webapps2023/authy/urls.py
from django.urls import path
from .views import login_page, login_user, logout_user, change_password
from django.conf.urls import include

app_name = 'authy'
urlpatterns = [
    path('login/', login_page, name='login_page'),
    path('login_user', login_user, name='login_user'),
    path('register', include('register.urls')),
    # path('register_user', register_user, name='register_user'),
    path('logout', logout_user, name='logout_user'),
    path('change_password', change_password, name='change_password'),
]

webapps2023/payapp/urls.py
from django.urls import path
from .views import dashboard_page, transfer_page, transactions_page, settings_page, help_page, update_profile, get_countries, search_user, create_transaction, accept_fund_request, cancel_fund_request, request_money, search_transactions


app_name = 'payapp'
urlpatterns = [
    path('', dashboard_page, name='dashboard_page'),
    path('transfer', transfer_page, name='transfer_page'),
    path('transactions', transactions_page, name='transactions_page'),
    path('settings', settings_page, name='settings_page'),
    path('help', help_page, name='help_page'),
    path('update_profile', update_profile, name='update_profile'),
    path('get_countries', get_countries, name='get_countries'),
    path('search_user', search_user, name='search_user'),
    path('create_transaction', create_transaction, name='create_transaction'),
    path('cancel_fund_request/<int:transaction_id>/', cancel_fund_request, name='cancel_fund_request'),
    # path('accept_fund_request/<int:transaction_id>/', accept_fund_request, name='accept_fund_request'),
    path('accept_fund_request/<int:transaction_id>/<int:sender_id>/<int:receiver_id>/<str:amount_from>/<str:amount_to>/', accept_fund_request, name='accept_fund_request'),
    path('request_money', request_money, name='request_money'),
    path('search_transactions', search_transactions, name='search_transactions'),

]

webapps2023/webapps2023/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from .views import home_page

app_name = 'webapps2023'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home_page'),
    path('auth/', include('authy.urls')),
    path('app/', include('payapp.urls')),
    path('conversion/', include('payapp.conversion_urls')),
]

webapps2023/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ca$hConnect {{ title }}</title>

    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <!--  Google Fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bungee&amp;display=swap">
    <!-- icon CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static "css/dashboard.css" %}">
    <link rel="stylesheet" href="{% static "css/styles.css" %}" >

    <!-- JavaScript -->
    {% load static %}
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>

    <!--  Custom JS-->
    <script src="{% static "js/bs-init.js" %}"></script>
    <script src="{% static "js/helper.js" %}"></script>
  </head>
  <body id="faded-pic-background">
    {% block content %}

    {% endblock %}

    <div class="toast-container position-fixed bottom-0 end-0 m-3">
      <div id="myAlert" class="toast {% if alert %}text-bg-danger{% else %}text-bg-success{% endif %} {% if error %}show{% else %}hide{% endif %}" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
          <div class="toast-body" id="feedback-msg">
            {{ error_msg }}
          </div>
          <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
      </div>
    </div>

  </body>
</html>

webapps2023/templates/base/header_app_base.html
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a
            class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 logo" href="{% url 'payapp:dashboard_page' %}">
        <h4 class="text-white mb-0">Ca$hConnect</h4>
    </a>
    <div>
        <button class="btn d-none d-md-block dropdown-toggle" type="button" data-bs-toggle="dropdown"
                data-bs-display="static" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="1em"
                 height="1em" viewBox="0 0 20 20" fill="none" class="fs-5 text-white">
                <path
                        d="M10 2C6.68632 2 4.00003 4.68629 4.00003 8V11.5858L3.29292 12.2929C3.00692 12.5789 2.92137 13.009 3.07615 13.3827C3.23093 13.7564 3.59557 14 4.00003 14H16C16.4045 14 16.7691 13.7564 16.9239 13.3827C17.0787 13.009 16.9931 12.5789 16.7071 12.2929L16 11.5858V8C16 4.68629 13.3137 2 10 2Z"
                        fill="currentColor"></path>
                <path d="M10 18C8.34315 18 7 16.6569 7 15H13C13 16.6569 11.6569 18 10 18Z" fill="currentColor">
                </path>
            </svg>
        </button>
        <ul class="dropdown-menu dropdown-menu-end bg-light shadow-lg" style="width: 300px;">
            <div class="d-flex justify-content-between mx-3 mb-3">
                <span class="text-muted small fw-bold">Notifications</span>
                           <a href="{% url 'payapp:transactions_page' %}" class="small text-decoration-none">view all</a>
            </div>

            {% if transactions|length > 0 %}
            {% for transaction in transactions|dictsortreversed:"transaction_date"|slice:":4" %}
            <li>
                <a class="dropdown-item py-0" href="#">
                    <div class="d-flex align-items-center">
                        <span class="me-2 text-danger" style="font-size: x-small">●</span>
                        <div class="d-grid">
                            <span class="text-wrap" style="font-size:small">

                                {% if transaction.status == "pending" %}
                                Request
                                {% else %}
                                    {% if transaction.sent_from.username == auth_user.username %}
                                        Sent
                                    {% else %}
                                        Received
                                    {% endif %}
                                {% endif %}

                                 payment of
                                <b>

<!--                                {% if transaction.sent_from.username == auth_user.username %}{{transaction.currency_from.symbol}}{% else %}{{transaction.currency_to.symbol}}{% endif %}-->
                                {% if transaction.sent_from.username == auth_user.username %}{{transaction.currency_from.symbol}}{{transaction.amount_from}}{% else %}{{transaction.currency_to.symbol}}{{transaction.amount_to}}{% endif %}

                                </b>

                                {% if transaction.status == "pending" %}
                                    {% if transaction.sent_from.username == auth_user.username %} from {% else %} to {% endif %}
                                {% else %}
                                    {% if transaction.sent_from.username == auth_user.username %} to {% else %} from {% endif %}
                                {% endif %}

                                <b>{{ transaction.sent_from.username }}</b>
                            </span>
                            <span class="text-muted" style="font-size:x-small">{{ transaction.transaction_date|date:"D d M h:i a" }}</span>
                        </div>
                    </div>
                </a>
            </li>

            <li>
                <hr class="dropdown-divider">
            </li>
            {% endfor %}
            {% else %}
            <span class="text-danger">No new notifications</span>
            {% endif %}

        </ul>
    </div>
    <ul class="dropdown-menu dropdown-menu-end" style="width: 300px !important;">
        {% if transactions|length > 0 %}
            {% for transaction in transactions %}
                <li>
                    <a class="dropdown-item py-0" href="#">
                        <div class="d-flex align-items-center">
                            <span class="me-2 text-danger">●</span>
                            <div class="d-grid">
                                <span class="text-wrap">RReceived payment of £{{ transaction.amount }} from {{ transaction.sent_from }}</span>
                                <span class="small text-black-50">{{ transaction.transaction_date|date:"h:iA" }}</span>
                            </div>
                        </div>
                    </a>
                </li>
                <li></li>
            {% endfor %}
        {% else %}
            <span class="text-danger">No new notifications</span>
        {% endif %}
    </ul>
    <button class="btn navbar-toggler position-absolute d-md-none collapsed" type="button"
            data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
</header>

webapps2023/templates/base/sidebar_base.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link {% if active_page == 'dashboard' %} active {% endif %}" href="{% url 'payapp:dashboard_page' %}" aria-current="page">
                    <svg
                            xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"
                            fill="none" class="align-text-bottom feather">
                        <path
                                d="M3 12L5 10M5 10L12 3L19 10M5 10V20C5 20.5523 5.44772 21 6 21H9M19 10L21 12M19 10V20C19 20.5523 18.5523 21 18 21H15M9 21C9.55228 21 10 20.5523 10 20V16C10 15.4477 10.4477 15 11 15H13C13.5523 15 14 15.4477 14 16V20C14 20.5523 14.4477 21 15 21M9 21H15"
                                stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round"></path>
                    </svg>
                    Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if active_page == 'transfer' %} active {% endif %}" href="{% url 'payapp:transfer_page' %}" aria-current="page">
                    <svg
                            xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"
                            fill="none" class="align-text-bottom feather">
                        <path d="M3 10H13C17.4183 10 21 13.5817 21 18V20M3 10L9 16M3 10L9 4"
                              stroke="currentColor" stroke-width="2" stroke-linecap="round"
                              stroke-linejoin="round"></path>
                    </svg>
                    Transfer</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if active_page == 'transactions' %} active {% endif %}" href="{% url 'payapp:transactions_page' %}" aria-current="page">
                    <svg
                            xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"
                            fill="none" class="align-text-bottom feather">
                        <path d="M8 7L20 7M20 7L16 3M20 7L16 11M16 17L4 17M4 17L8 21M4 17L8 13"
                              stroke="currentColor" stroke-width="2" stroke-linecap="round"
                              stroke-linejoin="round"></path>
                    </svg>
                    Transactions</a>
            </li>
        </ul>
        <div class="position-absolute bottom-0 pb-3 w-100">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link {% if active_page == 'settings' %} active {% endif %}" href="{% url 'payapp:settings_page' %}" aria-current="page">
                        <svg
                                xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"
                                fill="none" class="align-text-bottom feather">
                            <path
                                    d="M10.3246 4.31731C10.751 2.5609 13.249 2.5609 13.6754 4.31731C13.9508 5.45193 15.2507 5.99038 16.2478 5.38285C17.7913 4.44239 19.5576 6.2087 18.6172 7.75218C18.0096 8.74925 18.5481 10.0492 19.6827 10.3246C21.4391 10.751 21.4391 13.249 19.6827 13.6754C18.5481 13.9508 18.0096 15.2507 18.6172 16.2478C19.5576 17.7913 17.7913 19.5576 16.2478 18.6172C15.2507 18.0096 13.9508 18.5481 13.6754 19.6827C13.249 21.4391 10.751 21.4391 10.3246 19.6827C10.0492 18.5481 8.74926 18.0096 7.75219 18.6172C6.2087 19.5576 4.44239 17.7913 5.38285 16.2478C5.99038 15.2507 5.45193 13.9508 4.31731 13.6754C2.5609 13.249 2.5609 10.751 4.31731 10.3246C5.45193 10.0492 5.99037 8.74926 5.38285 7.75218C4.44239 6.2087 6.2087 4.44239 7.75219 5.38285C8.74926 5.99037 10.0492 5.45193 10.3246 4.31731Z"
                                    stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round"></path>
                            <path
                                    d="M15 12C15 13.6569 13.6569 15 12 15C10.3431 15 9 13.6569 9 12C9 10.3431 10.3431 9 12 9C13.6569 9 15 10.3431 15 12Z"
                                    stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round"></path>
                        </svg>
                        Settings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if active_page == 'help' %} active {% endif %}" href="{% url 'payapp:help_page' %}" aria-current="page">
                        <svg class="align-text-bottom feather" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none">
                            <path d="M13 16H12V12H11M12 8H12.01M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                        </svg>
                        Help</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authy:logout_user' %}" aria-current="page">
                        <svg
                                xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"
                                fill="none" class="align-text-bottom feather">
                            <path
                                    d="M17 16L21 12M21 12L17 8M21 12L7 12M13 16V17C13 18.6569 11.6569 20 10 20H6C4.34315 20 3 18.6569 3 17V7C3 5.34315 4.34315 4 6 4H10C11.6569 4 13 5.34315 13 7V8"
                                    stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round"></path>
                        </svg>
                        Log out</a>
                </li>
            </ul>
        </div>
    </div>
</nav>